queue_clean_up:
  cron: '0 0 * * *'
  class: 'DeadlineEventsCleanupJob'
  queue: default
  args:
  description: 'Вывод в log-файл'
queue_manage_users:
  cron: '* * * * *'
  class: 'ManageUsersJob'
  queue: users
  args:
  description: 'Управление пользователями через файл'